spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sistema_inventario}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:06OC2005}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
